image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@13.1.1
  - npm install
  - ng build --prod --base-href /LesPotionsDeMana/
  - mkdir public
  - mv prod/LesPotionsDeMana/* public/
  artifacts:
    paths:
    - public
  only:
  - main