image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  stage: deploy
  script:
  - npm install -g @angular/cli@16.13.1
  - npm install
  - ng build --prod --base-href /my-project/
  - mkdir public
  - mv prod/lesPotionsDeMana/* public/
  artifacts:
    paths:
    - public
  only:
  - main